### ISSUE TITLE
Effects do not transfer between servers when switching servers

### ISSUE THREAD

**Issue by thiagogebrimm** [Minebench/SyncInv#9]
#### Used Version

 SyncInv build 78
 
#### Config

 ```yaml
 # Debugging mode to log more about what's going on
debug: false

# Redis messenger settings
redis:
  host: a
  port: a
  timeout: a
  password: 'a'
# you can also directly set the uri for example like this (directly set values overwrite uri parameter 'though):
# uri: redis://password1@localhost:6379/database?timeout=60s [&database=database]

# Whether or not the plugin should query inventories on other server
# or just move the player to the server with the newest inventory
query-inventories: true

# The name of the group this server is in. Set that to the same value
# on all servers which's data you want to get synced.
server-group: survival

# The name of this server. If you don't want to query inventories then
# this has to be the same as the name in your BungeeCord's config.yml
server-name: azul # CHANGE THIS!

# A list of server names that are required to answer to request
# That way you can stop issues when a server isn't online that usually should be
required-servers: []

# Whether or not we should sync the data with all servers in a group
# when a player logs out. Use this if your servers have the tendency
# to not always be online.
sync-with-group-on-logout: true

# Store player data even if the player never joined the server
# This will create a player.dat when the data is synced and most likely
# breaks first join detection of other plugins
store-unknown-players: true

# Whether to create a missing 'world' world which is required
# for unknown player storage to work
create-world: true

# The amount of seconds we should maximally wait for all servers to
# respond to a query
query-timeout: 5

# Whether or not we should load the data from queries that timed out
# This might run into issues if the server with the most recent data
# is not online at the moment of querying!
# It will basically disable the required-servers function
apply-timed-out-queries: false

# What to sync
sync:
  # Should the plugin sync player inventory items?
  inventory: true
  # Should the plugin sync player enderchest items?
  enderchest: true
  # Should the plugin try sync the player gamemode? (Only works when the player is actually online, not for offline storage)
  gamemode: true
  # Should the plugin sync the player experience?
  experience: true
  # Should the plugin sync the player's health, max health and health scaling?
  health: true
  # Should the plugin to sync the player's food level?
  hunger: true
  # Should the plugin to sync the player's saturation?
  saturation: true
  # Should the plugin to sync the player's exhaustion?
  exhaustion: true
  # Should the plugin to sync the player's air level?
  air: true
  # Should the plugin sync the player's on fire state and fire duration?
  fire: true
  # Should the plugin to sync the player's no-damage-ticks?
  no-damage-ticks: true
  # Should the plugin to sync the player's current velocity?
  velocity: true
  # Should the plugin sync the player's current fall distance?
  # (Might kill player on other server when log in on the ground)
  fall-distance: false
  # Should the plugin try to sync player effects? (Only works when the player is actually online, not for offline storage)
  effects: true
  # Should the plugin try to sync persistent nbt data on the player object?
  persistent-data: true
  # Should the plugin sync player advancement progress?
  advancements: true
  # Should the plugin sync general player statistics?
  general-statistics: true
  # Should the plugin sync entity player statistics?
  entity-statistics: true
  # Should the plugin sync item player statistics?
  item-statistics: true
  # Should the plugin sync block player statistics?
  block-statistics: true
  # Should the plugin try to keep maps in sync?
  maps: true

# Language settings
lang:
  cant-pickup-exp: "&cVocê só pode coletar XP quando seus dados forem carregados completamente!"
  cant-pickup-items: "&cVocê só pode coletar itens quando seus dados forem carregados completamente!"
  cant-drop-items: "&cVocê só pode jogar itens quando seus dados forem carregados completamente!"
  cant-move: "&cVocê só pode se mover quando seus dados forem carregados completamente!"
  wait-for-loading: "&cAguarde enquanto seus dados são carregados..."
  cant-load-data: "&cNão foi possível carregar seus dados!\n\nEntre em contato conosco caso o problema persistir: discord.gg/rederevo"
 ```
 
#### Environment description
Purpur 1.19.3

#### What did you expect to happen?
effects pass between servers
